package auth

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DiscoverUser performs a lean dedupe check to see if the mobile number exists
func (h *Handler) DiscoverUser(c *gin.Context) {
	mobile := c.Query("mobile")
	if mobile == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Mobile number is required"})
		return
	}

	// 1. Execute the SQL query generated by sqlc from discovery.sql
	profiles, err := h.queries.CheckMobileDedupe(c.Request.Context(), mobile)
	if err != nil {
		h.logger.Error("Discovery lookup failed", "error", err, "mobile", mobile)
		c.JSON(http.StatusInternalServerError, gin.H{
			"error":   "Database lookup failed",
			"details": err.Error(),
		})
		return
	}

	// 2. Logic: If no profiles found, it's a brand new user
	if len(profiles) == 0 {
		c.JSON(http.StatusOK, gin.H{
			"status":  "NEW_USER",
			"message": "Welcome to DealJosh! Please proceed to signup.",
		})
		return
	}

	// 3. Logic: Existing user (Owner or Staff)
	c.JSON(http.StatusOK, gin.H{
		"status":   "EXISTING_USER",
		"profiles": profiles,
		"message":  "User identified. Requesting OTP...",
	})
}
